### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by jianshu93** [lazear/sage#145]
Hello Sage team,

It seems I can't compile using rust stable 1.79 or 1.80:

error[E0282]: type annotations needed for `Box<_>`
  --> /Users/jianshuzhao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

The binary did work though. 

Thanks,

Jianshu

**Comment by lazear** [comment]
Thanks for the report - looks like an issue in a sub dependency, I'll see if I can bump some versions to get it to compile with the newest version of Rust
